# Generated by Django 5.0.2 on 2024-02-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creer_annonce',
            name='created_by',
        ),
    ]
