# Generated by Django 5.0.2 on 2024-02-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_remove_creer_annonce_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creer_annonce',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('annonce_achieve', 'annonce_achieve')], default='pending', max_length=20),
        ),
    ]
