# Generated by Django 5.0.2 on 2024-02-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_alter_creer_annonce_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creer_annonce',
            name='photo_voiture',
            field=models.FileField(upload_to='media/'),
        ),
    ]
